
CREATE TABLE TESTE (
ATT1 INTEGER NN KEY,
ATT2 STRING NN ORD,
ATT3 INTEGER);
INSERT INTO TESTE VALUES (1,"testando",20);
INSERT INTO TESTE VALUES (2,"testando123",30);
INSERT INTO TESTE VALUES (3,"Testando",20);
INSERT INTO TESTE VALUES (4,"testando",20);
INSERT INTO TESTE VALUES (5,"testando",20);
INSERT INTO TESTE VALUES (6,"testando",20);
INSERT INTO TESTE VALUES (7,"testando",20);
INSERT INTO TESTE VALUES (8,"testando",20);
INSERT INTO TESTE VALUES (9,"testando",20);
INSERT INTO TESTE VALUES (10,"testando",20);
SELECT ATT1,ATT3 FROM TESTE;