
CREATE TABLE TESTE (
ATT1 INTEGER NN KEY,
ATT2 STRING NN ORD,
ATT3 INTEGER);
CREATE TABLE TESTE2 (
ATR1 INTEGER NN KEY,
ATR2 STRING NN ORD,
ATR3 INTEGER);
INSERT INTO TESTE VALUES (1,"testando",20);
INSERT INTO TESTE VALUES (2,"testando123",30);
INSERT INTO TESTE VALUES (3,"Testando",20);
INSERT INTO TESTE VALUES (4,"testando",20);
INSERT INTO TESTE VALUES (5,"testando",20);
INSERT INTO TESTE VALUES (6,"testando",20);
INSERT INTO TESTE VALUES (7,"testando",20);
INSERT INTO TESTE VALUES (8,"testando",20);
INSERT INTO TESTE VALUES (9,"testando",20);
INSERT INTO TESTE VALUES (10,"testando",20);
INSERT INTO TESTE2 VALUES (1,"testando",20);
INSERT INTO TESTE2 VALUES (2,"testando123",30);
INSERT INTO TESTE2 VALUES (3,"Testando",20);
INSERT INTO TESTE2 VALUES (4,"testando",20);
INSERT INTO TESTE2 VALUES (5,"testando",20);
INSERT INTO TESTE2 VALUES (6,"testando",20);
INSERT INTO TESTE2 VALUES (7,"testando",20);
INSERT INTO TESTE2 VALUES (8,"testando",20);
INSERT INTO TESTE2 VALUES (9,"testando",20);
INSERT INTO TESTE2 VALUES (10,"testando",20);
SELECT ATT1,ATR2 FROM (TESTE JOIN TESTE2 ON ATT1=ATR1);